import { Inter } from "next/font/google";
import "./globals.css";
import ThemeRegistry from '/utils/ThemeRegistry'
import * as React from 'react';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Aleksa Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeRegistry options={{ key: 'mui-theme' }}>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
